### ISSUE TITLE
it does not work for me too 

### ISSUE THREAD

**Issue by alexseyk** [blmage/duolingo-word-bank-dnd#38] opened 2020-11-27 02:15 UTC
Using chrome  on mac os Mojave  even after i disabled all Duo related extensions .
but It works if i change the screen(browser) to a tablet (mobile)  size 

![ezgif-1-d7d9caa26bdd](https://user-images.githubusercontent.com/60418150/100403269-fe9c1d80-3090-11eb-9930-77a597c662cc.gif)

**Comment by blmage** [comment] 2020-11-27 11:02
Closing this as a duplicate of #37, but your demo was *really* useful, thank you very much!

**Closed as completed by blmage** 2020-11-27 11:02 UTC
Labels: bug, duplicate
